--------------------------------------------------------
-- Archivo creado  - domingo-octubre-06-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HABITACION
--------------------------------------------------------

  CREATE TABLE "FSI_MS_BD_ET"."HABITACION" 
   (	"DISPONIBLE" NUMBER(1,0), 
	"ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NUMERO" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table RESERVA
--------------------------------------------------------

  CREATE TABLE "FSI_MS_BD_ET"."RESERVA" 
   (	"FECHA_FIN" DATE, 
	"FECHA_INICIO" DATE, 
	"HABITACION_ID" NUMBER(19,0), 
	"ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ESTADO_RESERVA" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"NOMBRE_CLIENTE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"TELEFONO_CLIENTE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into FSI_MS_BD_ET.HABITACION
SET DEFINE OFF;
Insert into FSI_MS_BD_ET.HABITACION (DISPONIBLE,ID,NUMERO) values ('1','73','101');
REM INSERTING into FSI_MS_BD_ET.RESERVA
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table HABITACION
--------------------------------------------------------

  ALTER TABLE "FSI_MS_BD_ET"."HABITACION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FSI_MS_BD_ET"."HABITACION" ADD CHECK (disponible in (0,1)) ENABLE;
  ALTER TABLE "FSI_MS_BD_ET"."HABITACION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "FSI_MS_BD_ET"."HABITACION" ADD UNIQUE ("NUMERO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVA
--------------------------------------------------------

  ALTER TABLE "FSI_MS_BD_ET"."RESERVA" MODIFY ("FECHA_FIN" NOT NULL ENABLE);
  ALTER TABLE "FSI_MS_BD_ET"."RESERVA" MODIFY ("FECHA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "FSI_MS_BD_ET"."RESERVA" MODIFY ("HABITACION_ID" NOT NULL ENABLE);
  ALTER TABLE "FSI_MS_BD_ET"."RESERVA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FSI_MS_BD_ET"."RESERVA" MODIFY ("NOMBRE_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "FSI_MS_BD_ET"."RESERVA" MODIFY ("TELEFONO_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "FSI_MS_BD_ET"."RESERVA" ADD CHECK (estado_reserva in ('ACTIVA','CANCELADA')) ENABLE;
  ALTER TABLE "FSI_MS_BD_ET"."RESERVA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVA
--------------------------------------------------------

  ALTER TABLE "FSI_MS_BD_ET"."RESERVA" ADD CONSTRAINT "FKTR5BG864M3DSEKO7GIF2BL239" FOREIGN KEY ("HABITACION_ID")
	  REFERENCES "FSI_MS_BD_ET"."HABITACION" ("ID") ENABLE;
